name: CI

on:
  push:
    branches:
      - main

jobs:
  compile:
    name: Compile and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Source Changes
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            themeChange:
              - 'client/**'
          list-files: 'shell'
      - name: Setup Node.js 18
        if: steps.filter.outputs.themeChange == 'true'
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        if: steps.filter.outputs.themeChange == 'true'
        run: npm ci
      - name: Compile
        if: steps.filter.outputs.themeChange == 'true'
        run: node scripts/compile.mjs ${{ steps.filter.outputs.themeChange_files }}
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: src